import requests
import json
import re
from PyQt5.QtMultimedia import QMediaContent,QMediaPlayer


url = "https://api.uomg.com/api/rand.music?sort=热歌榜&format=json"
html = requests.post(url)
text = html.json()['data']
url = text['url']

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'music.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaContent,QMediaPlayer



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.play = QtWidgets.QPushButton(Form)
        self.play.setGeometry(QtCore.QRect(40, 220, 93, 28))
        self.play.setObjectName("play")
        self.stop = QtWidgets.QPushButton(Form)
        self.stop.setGeometry(QtCore.QRect(260, 220, 93, 28))
        self.stop.setObjectName("stop")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 311, 181))
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.play.clicked.connect(self.play_music)
        self.player = QMediaPlayer()
        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)
        self.timer.start()
        self.timer.timeout.connect(self.check_music_status)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    # 按钮文本    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.play.setText(_translate("Form", "播放"))
        self.stop.setText(_translate("Form", "停止"))
        self.label.setText(_translate("Form", self.TextLabel()))
    
    # 文本框
    def TextLabel(self):
        TextLabel = ""
        return TextLabel
# 播放 自动下一首 停止
    def play_music(self):
        
        content = QMediaContent(QtCore.QUrl(url))
        self.player.setMedia(content)
        self.player.setVolume(50)
        self.player.play()
        


    def check_music_status(self):
        player_status = self.player.mediaStatus()
        print(player_status)
        
        # print("音乐时间：",player_duration)
        # print("当前播放器状态",player_status)
        if player_status == 7:
            self.play_music()




import sys
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
